name: Continuous Deployment (CD)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checar código
      uses: actions/checkout@v2

    - name: Configuração do ambiente
      run: echo "Deployment configuration, but not implemented"
